---
title: "Introduction to AutoPop"
output:
  html_document:
    df_print: paged
  pdf_document:
    fig_caption: yes
    extra_dependencies: flafter
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(kableExtra)
library(mathjaxr)
library(knitr)
```



## Summary
AutoPop is an R-based joint-dynamic population simulation for diploids, triploids, and autotetraploids. For details on these methods, see [Gaynor et al. 2023](). To summarize, this package contains a stochastic stage-structured matrix population dynamics model for diploid, triploid, and autotetraploid perennial plants with overlapping generations. Specifically, yhis model includes three cytotypes (diploid, triploids, and autotetraploids), as well as two life stages, in regards to reproductive ability (immature and mature), for a total of six stages each represented by $c_{i,j}$ where i = \{2, 3, 4\} and j = \{1,2\}.

Each time step includes three processes: 

-   <span style="color:green">Reproduction</span>
-   <span style="color:red">Survival</span>
-   <span style="color:blue">Maturation</span>


$$ 
=
\left(\begin{array}{cc} 
C_{2,1} \\
C_{3,1} \\
C_{4,1} \\
C_{2,2} \\
C_{3,2} \\
C_{4,2} \\
\end{array}\right)
\left(\begin{array}{cc} 
\color{red}{S_{2,1}} & 0 & 0 & \color{green}{F_{2,2}} & \color{green}{F_{2,3}} & \color{green}{F_{2,4}}\\ 
0 & \color{red}{S_{3,1}} & 0 & \color{green}{F_{3,2}} & \color{green}{F_{3,3}} & \color{green}{F_{3,4}}\\
0 & 0 & \color{red}{S_{4,1}} & \color{green}{F_{4,2}} & \color{green}{F_{4,3}} & \color{green}{F_{4,4}}\\
\color{blue}{M_{2}}& 0 & 0 & \color{red}{S_{2,2}} & 0 & 0 \\
0 & \color{blue}{M_{3}} & 0 & 0 & \color{red}{S_{3,2}} & 0\\
0 & 0 & \color{blue}{M_{4}} & 0 & 0 & \color{red}{S_{4,2}} \\
\end{array}\right)
$$



or in matrix notation:

\begin{equation}
\mathbf{C_{t+1}} = \mathbf{A}\mathbf{C_{t}}.
\end{equation}


<br>

## Model Parameters

**Table 1**: Summary of model parameters and definitions. Color indicates processes: reproduction (green), survival (red), and maturation (blue).

| In-text | In-code |    Definition        | 
|:--------:|:--------:|:-------------------------------------|
|$generations$ | $generations$ |	Number of time steps 		| 
|$init.pop$ |   $init.pop$ 	| Initial population size 	 |
|$\color{green}{gnum}$  |$\color{green}{gnum.base}$   |  Number of gametes produced by a mature individual     |
|$\color{green}{d}$ | $\color{green}{d}$ |   	Strength of density dependence 	 |
||$\color{green}{density.type}$ | Sets type of density dependency utilized when defining number of gametes per individual. Options: "all" or "like-cytotype" | 
|$\color{green}{b}$    |$\color{green}{b}$ | Frequency of unreduced gamete formation |
|$\color{green}{v}$ |$\color{green}{cc}$  | Proportion of viable triploid gametes 		|
|$\color{green}{s}$|$\color{green}{s}$ 	| Selfing rate      |
|$\color{green}{mc}$ | $\color{green}{mc}$ | Strength of mating choice 	|
|$\color{red}{a_{i,i}}$ |$\color{red}{aii.vec}$ | Cytotype-specific immature survival probability 	|
|$\color{red}{\mu}$ | $\color{red}{as.msurv}$	| Mean mature survival probability 	|
|$\color{red}{ci}$| $\color{red}{env.ci}$		| Proportion of environmental variance	|
|$\color{blue}{as.matur}$|$\color{blue}{as.matur}$	|  Cytotype-specific maturation probability 	|                                                                                                                                                                  



